#!/bin/bash
#
#SBATCH --job-name=LobsterNormal
#SBATCH --mail-user=janine.george@uclouvain.be
#SBATCH --mail-type=ALL
#SBATCH --cpus-per-task=1
#SBATCH --partition=Def
#SBATCH --ntasks=32
#SBATCH --time=0-24:00:00
#SBATCH --mem-per-cpu=4096M


cd /globalscratch/users/j/g/jgeorge/Calculation_Bandstructure_GaAs/LobsterNormal
module purge
export I_MPI_PMI_LIBRARY='/usr/lib64/libpmi.so'
export PATH=/home/ucl/naps/jgeorge/bin:/home/ucl/naps/jgeorge/miniconda3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/ucl/naps/jgeorge/bin
source /home/ucl/naps/yugd/software/virtualenv/bin/activate
source /home/ucl/naps/yugd/intel/compilers_and_libraries_2016.1.150/linux/bin/ifortvars.sh intel64

export OMP_NUM_THREADS=1
unset SLURM_CPUS_PER_TASK
CPU=32
MPIRUN="srun"
MPIOPT="-n $CPU"
VASP="vasp_std"

${MPIRUN} ${MPIOPT} ${VASP}


